apiVersion: run.tanzu.vmware.com/v1alpha1    
kind: TanzuKubernetesCluster                 
metadata:
  name: tkc-cluster-01                            #TKG Cluster Nmee                                
  namespace: testns                          #Namespace to deploy cluster to                     
spec:
  distribution:
    version: v1.18	                             #Resolves to the latest v1.17 image (v1.17.8+vmware.1-tkg.1.5417466)
  topology:
    controlPlane:
      count: 1                                   #Number of control plane nodes                       
      class: best-effort-xsmall                  #Cluster VM size and guaranteed resources or best-effort
      storageClass: kubernetes                 #Specific storage class for control plane       
    workers:
      count: 2                                   #Number of worker nodes                     
      class: best-effort-xsmall                  #Cluster VM size and guaranteed resources or best-effort          
      storageClass: kubernetes                 #Specific storage class for workers     
  settings:
    network:
 #     cni:                                      #Uncomment for Calico.  Antrea is default as of 1.17
 #       name: calico                            #Uncomment for Calico.  Antrea is default as of 1.17
      services:
        cidrBlocks: ["198.51.100.0/12"]          #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.0.2.0/16"]             #Cannot overlap with Supervisor Cluster
    storage:
      classes: ["kubernetes"]                  #Named PVC storage classes
      defaultClass: kubernetes                 #Default PVC storage class
