apiVersion: v1
kind: Pod
metadata:
  name: tinytools
spec:
  containers:
  - name: tinytools
    image: giantswarm/tiny-tools
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
