apiVersion: run.tanzu.vmware.com/v1alpha1    
kind: TanzuKubernetesCluster                 
metadata:
  name: tkc-app-01                               #TKG Cluster Nmee                                
  namespace: app01                               #vSphere namespace to deploy cluster to                     
spec:
  distribution:
    version: v1.20	                             #Resolves to the latest v1.20 image or use specific version(1.20.7+vmware.1-tkg.1.7fb9067 )
  topology:
    controlPlane:
      count: 1                                   #Number of control plane nodes                       
      class: best-effort-xsmall                  #Cluster VM size and guaranteed resources or best-effort
      storageClass: kubernetes                   #Specific storage class for control plane  
 #     volumes:                                   #Optional additional storage
 #       - name: etcd
 #         mountPath: /var/lib/etcd
 #         capacity:
 #           storage: 4Gi     
    workers:
      count: 2                                   #Number of worker nodes                     
      class: best-effort-xsmall                  #Cluster VM size and guaranteed resources or best-effort          
      storageClass: kubernetes                   #Specific storage class for workers  
 #     volumes:                                   #Optional additional storage mount for containers
 #       - name: containerd
 #         mountPath: /var/lib/containerd
 #         capacity:
 #           storage: 30Gi        
  settings:
    network:
 #     cni:                                      #Uncomment for Calico.  Antrea is default as of 1.17
 #       name: calico                            #Uncomment for Calico.  Antrea is default as of 1.17
      services:
        cidrBlocks: ["198.51.100.0/24"]          #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.0.2.0/22"]             #Cannot overlap with Supervisor Cluster
    storage:
      classes: ["kubernetes"]                  #Named PVC storage classes
      defaultClass: kubernetes                #Default PVC storage class