apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: gcr.io/google-containers/busybox:latest
#    image: busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
#  imagePullSecrets:
#  - name: regcred
#  restartPolicy: Always
